import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';

const SRC = 'src';

function walk(dir) {
  let results = [];
  const list = readdirSync(dir);
  for (const file of list) {
    const filePath = join(dir, file);
    const stat = statSync(filePath);
    if (stat.isDirectory()) {
      results = results.concat(walk(filePath));
    } else if (file.endsWith('.vue')) {
      results.push(filePath);
    }
  }
  return results;
}

const uiDir = join(SRC, 'components', 'ui');
const vueFiles = walk(SRC).filter(f => !f.replace(/\\/g, '/').includes('/components/ui/'));

const replacements = [
  { pattern: /bg-slate-100 dark:bg-slate-700/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-800/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-50 dark:bg-slate-800/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-900/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-900(?![/])/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-950/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-950/g, replacement: 'bg-card' },
  { pattern: /text-slate-700 dark:text-slate-200/g, replacement: 'text-foreground' },
  { pattern: /text-slate-800 dark:text-slate-100/g, replacement: 'text-foreground' },
  { pattern: /text-slate-900 dark:text-white/g, replacement: 'text-foreground' },
  { pattern: /text-slate-800 dark:text-slate-200/g, replacement: 'text-foreground' },
  { pattern: /text-slate-700 dark:text-slate-300/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-500 dark:text-slate-400/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-600 dark:text-slate-300/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-400 dark:text-slate-500/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-600 dark:text-slate-200/g, replacement: 'text-foreground' },
  { pattern: /text-slate-500 dark:text-slate-300/g, replacement: 'text-muted-foreground' },
  { pattern: /border-slate-200 dark:border-slate-700/g, replacement: 'border-border' },
  { pattern: /border-slate-200 dark:border-slate-800/g, replacement: 'border-border' },
  { pattern: /border-slate-100 dark:border-slate-700/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/80 dark:border-slate-800\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/50 dark:border-slate-800/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/50 dark:border-slate-700/g, replacement: 'border-border' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /bg-slate-200 dark:bg-slate-700/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-800/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-600/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200\/70 dark:bg-slate-700\/70/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-600/g, replacement: 'bg-muted' },
  { pattern: /(?<!-)bg-slate-50(?!\s| dark:)/g, replacement: 'bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100\/80 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50\/80 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-600/g, replacement: 'hover:bg-accent' },
  { pattern: /border-slate-200 dark:border-slate-700\/50/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/60 dark:border-slate-700\/60/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/50 dark:border-slate-700\/50/g, replacement: 'border-border' },
  { pattern: /divide-slate-200 dark:divide-slate-800/g, replacement: 'divide-border' },
  { pattern: /divide-slate-200 dark:divide-slate-700/g, replacement: 'divide-border' },
  { pattern: /bg-slate-50 dark:bg-slate-900\/40/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-900\/30/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-900\/50/g, replacement: 'bg-card' },
  { pattern: /bg-white\/70 dark:bg-slate-900\/40/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800\/50/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-800\/50/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-800\/30/g, replacement: 'bg-card' },
  { pattern: /bg-slate-100 dark:bg-slate-800\/50/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-800\/80/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100\/80 dark:bg-slate-800\/80/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100\/90 dark:bg-slate-700\/90/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100\/90 dark:bg-slate-800\/90/g, replacement: 'bg-secondary' },
  { pattern: /border-slate-300 dark:border-slate-600/g, replacement: 'border-border' },
  { pattern: /border-slate-200 dark:border-slate-600/g, replacement: 'border-border' },
  { pattern: /border-slate-100 dark:border-slate-800/g, replacement: 'border-border' },
  { pattern: /border-slate-100 dark:border-slate-800\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-200 dark:border-slate-800\/80/g, replacement: 'border-border' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-white dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /bg-slate-50 dark:bg-slate-700/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-800\/50/g, replacement: 'bg-card' },
  { pattern: /text-slate-700 dark:text-slate-100/g, replacement: 'text-foreground' },
  { pattern: /text-slate-800 dark:text-white/g, replacement: 'text-foreground' },
  { pattern: /text-slate-900 dark:text-slate-100/g, replacement: 'text-foreground' },
  { pattern: /text-slate-900 dark:text-slate-50/g, replacement: 'text-foreground' },
  { pattern: /text-slate-700 dark:text-slate-400/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-600 dark:text-slate-400/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-500 dark:text-slate-300/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-400 dark:text-slate-300/g, replacement: 'text-muted-foreground' },
  { pattern: /text-slate-400 dark:text-slate-600/g, replacement: 'text-muted-foreground' },
  { pattern: /bg-slate-50 dark:bg-\[#111827\]/g, replacement: 'bg-card' },
  { pattern: /bg-slate-900 dark:bg-slate-50/g, replacement: 'bg-foreground' },
  { pattern: /bg-slate-50 dark:bg-slate-800\/80/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800\/80/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-900\/40/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-900\/20/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800\/50/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-900\/50/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-800\/70/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800\/70/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-700/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-900\/30/g, replacement: 'bg-card' },
  { pattern: /bg-slate-100 dark:bg-slate-700\/50/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-600/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-900\/40/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-900\/30/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-900\/50/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-800\/30/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-800\/70/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-700\/70/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-700\/80/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-200 dark:bg-slate-700\/50/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-800\/50/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-600\/50/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-700/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-800/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-600\/50/g, replacement: 'bg-muted' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-100/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-200/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-300/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-800 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-100/g, replacement: 'hover:bg-accent' },
  { pattern: /border-slate-200\/70 dark:border-slate-800\/70/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/60 dark:border-slate-800\/60/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/70 dark:border-slate-700/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/90 dark:border-slate-600\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/90 dark:border-slate-700\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-300 dark:border-slate-700/g, replacement: 'border-border' },
  { pattern: /border-slate-300 dark:border-slate-800/g, replacement: 'border-border' },
  { pattern: /border-slate-200 dark:border-slate-800\/50/g, replacement: 'border-border' },
  { pattern: /border-slate-200 dark:border-slate-700\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-100 dark:border-slate-700\/50/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/50 dark:border-slate-800\/50/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/50 dark:border-slate-700\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-100\/80 dark:border-slate-800\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/80 dark:border-slate-700\/80/g, replacement: 'border-border' },
  { pattern: /border-slate-200\/80 dark:border-slate-800/g, replacement: 'border-border' },
  { pattern: /border-slate-100 dark:border-slate-800\/80/g, replacement: 'border-border' },
  { pattern: /bg-slate-50 dark:bg-slate-700\/50/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-700\/30/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-800\/40/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800\/40/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-700\/50/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800\/30/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-900\/80/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-700\/30/g, replacement: 'bg-card' },
  { pattern: /bg-white\/70 dark:bg-slate-800\/70/g, replacement: 'bg-card' },
  { pattern: /bg-white\/80 dark:bg-slate-800\/80/g, replacement: 'bg-card' },
  { pattern: /bg-white\/90 dark:bg-slate-900\/90/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-900\/80/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-900\/60/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-900\/60/g, replacement: 'bg-card' },
  { pattern: /bg-slate-50 dark:bg-slate-800\/60/g, replacement: 'bg-card' },
  { pattern: /bg-white dark:bg-slate-800\/60/g, replacement: 'bg-card' },
  { pattern: /bg-slate-100 dark:bg-slate-800\/60/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-700\/60/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-900\/60/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-800\/40/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-700\/40/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-900\/80/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-800\/90/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-100 dark:bg-slate-700\/90/g, replacement: 'bg-secondary' },
  { pattern: /bg-slate-200 dark:bg-slate-800\/50/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-700\/80/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-800\/80/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-900\/50/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-600\/80/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-700\/60/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-200 dark:bg-slate-800\/60/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-700\/50/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-800\/50/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-700\/80/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-800\/80/g, replacement: 'bg-muted' },
  { pattern: /bg-slate-300 dark:bg-slate-600\/80/g, replacement: 'bg-muted' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-600\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-800\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-200/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-300/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-200/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-100/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-600/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-800/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-700/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-300 dark:hover:bg-slate-900/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/50/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/80/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/70/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/30/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/20/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/40/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/60/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-600\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-600\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-600\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-800\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-800\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-800\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-700\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-700\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-700\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-50 dark:hover:bg-slate-900\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-100 dark:hover:bg-slate-900\/90/g, replacement: 'hover:bg-accent' },
  { pattern: /hover:bg-slate-200 dark:hover:bg-slate-900\/90/g, replacement: 'hover:bg-accent' },
];

let totalChanges = 0;

for (const file of vueFiles) {
  let content = readFileSync(file, 'utf8');
  let changed = false;

  for (const { pattern, replacement } of replacements) {
    const newContent = content.replace(pattern, replacement);
    if (newContent !== content) {
      content = newContent;
      changed = true;
    }
  }

  if (changed) {
    writeFileSync(file, content, 'utf8');
    totalChanges++;
    console.log(`Updated: ${file}`);
  }
}

console.log(`\nTotal files updated: ${totalChanges}`);
