#!/usr/bin/env bash
set -euo pipefail

OUT="/etc/nginx/snippets/awesomeiwb-realip.conf"
TMP="$(mktemp)"

{
  echo "# generated by refresh-cf-realip.sh"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  curl -fsSL https://www.cloudflare.com/ips-v4 | while read -r cidr; do
    [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
  done
  curl -fsSL https://www.cloudflare.com/ips-v6 | while read -r cidr; do
    [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
  done
} > "$TMP"

install -D -m 0644 "$TMP" "$OUT"
rm -f "$TMP"
echo "refreshed: $OUT"
