-- Migration: local admin accounts for emergency login
-- Date: 2026-05-08

-- Local accounts table: stores password hashes for emergency admin login
-- Completely isolated from OAuth/Casdoor users
CREATE TABLE IF NOT EXISTS local_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'ops' CHECK (role IN ('ops')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_login_at TIMESTAMPTZ,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for username lookups
CREATE INDEX IF NOT EXISTS local_accounts_username_idx ON local_accounts (username);

-- Index for active account lookups
CREATE INDEX IF NOT EXISTS local_accounts_active_idx ON local_accounts (username, is_active) WHERE is_active = true;

-- Add updated_at trigger for local_accounts table
DROP TRIGGER IF EXISTS local_accounts_updated_at ON local_accounts;
CREATE TRIGGER local_accounts_updated_at
  BEFORE UPDATE ON local_accounts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Insert the default super admin account
-- Password hash will be generated by the application on first startup
-- The hash below is a placeholder; the app will check and update it
INSERT INTO local_accounts (username, password_hash, role, is_active)
VALUES ('lincube', '$argon2id$v=19$m=65536,t=3,p=4$PLACEHOLDER$PLACEHOLDER', 'ops', true)
ON CONFLICT (username) DO NOTHING;
