export const API = {
  auth: {
    login: '/api/auth/login',
    callback: '/api/auth/callback',
    me: '/api/auth/me',
    logout: '/api/auth/logout',
    capabilities: '/api/capabilities',
    userAvatar: '/api/user/avatar',
    userAvatarSource: '/api/user/avatar-source',
    userRename: '/api/user/name',
  },
  catalog: {
    categories: '/api/categories',
    projects: '/api/projects',
    stats: '/api/stats',
    stories: '/api/stories',
    articles: '/api/articles',
    articleDetail: (slug: string) => `/api/articles/${encodeURIComponent(slug)}`,
    articleComments: (slug: string) => `/api/articles/${encodeURIComponent(slug)}/comments`,
    articleCommentReplies: (id: string) => `/api/article-comments/${encodeURIComponent(id)}/replies`,
  },
  feedback: {
    list: '/api/feedback',
    detail: (id: string) => `/api/feedback/${encodeURIComponent(id)}`,
    replies: (id: string) => `/api/feedback/${encodeURIComponent(id)}/replies`,
  },
  upload: {
    image: '/api/upload',
  },
  submissions: {
    list: '/api/submissions',
    dev: '/api/dev/submissions',
  },
  admin: {
    categories: '/api/admin/categories',
    projects: '/api/admin/projects',
    submissions: '/api/admin/submissions',
    moderationComments: '/api/admin/moderation/comments',
    moderationBugs: '/api/admin/moderation/bugs',
    users: '/api/admin/users',
    auditLogs: '/api/admin/audit-logs',
    media: '/api/admin/media',
    dashboard: '/api/admin/dashboard',
    roleTemplates: '/api/admin/role-templates',
    articles: '/api/admin/articles',
    articleDetail: (id: string) => `/api/admin/articles/${encodeURIComponent(id)}`,
    articlePublish: (id: string) => `/api/admin/articles/${encodeURIComponent(id)}/publish`,
    articleBacklinks: (id: string) => `/api/admin/articles/${encodeURIComponent(id)}/backlinks`,
    articleRevisions: (id: string) => `/api/admin/articles/${encodeURIComponent(id)}/revisions`,
    articleRevisionDetail: (id: string, revId: string) => `/api/admin/articles/${encodeURIComponent(id)}/revisions/${encodeURIComponent(revId)}`,
    articleRevisionRollback: (id: string, revId: string) => `/api/admin/articles/${encodeURIComponent(id)}/revisions/${encodeURIComponent(revId)}/rollback`,
    articlePresenceHeartbeat: (id: string) => `/api/admin/articles/${encodeURIComponent(id)}/presence/heartbeat`,
    articlePresence: (id: string) => `/api/admin/articles/${encodeURIComponent(id)}/presence`,
    articleComments: (slug: string) => `/api/articles/${encodeURIComponent(slug)}/comments`,
    articleCommentUpdate: (id: string) => `/api/admin/article-comments/${encodeURIComponent(id)}`,
    articleCommentDelete: (id: string) => `/api/admin/article-comments/${encodeURIComponent(id)}`,
    articleCommentReplies: (id: string) => `/api/article-comments/${encodeURIComponent(id)}/replies`,
    articleAnnotations: (id: string) => `/api/admin/articles/${encodeURIComponent(id)}/annotations`,
    articleAnnotationDetail: (id: string) => `/api/admin/article-annotations/${encodeURIComponent(id)}`,
    mediaTags: (id: string) => `/api/admin/media/${encodeURIComponent(id)}/tags`,
    mediaBatchTag: '/api/admin/media/batch-tag',
    mediaBatchDelete: '/api/admin/media/batch-delete',
    organizations: '/api/admin/organizations',
    organizationDetail: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}`,
    organizationApprove: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}/approve`,
    organizationReject: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}/reject`,
    organizationMemberSearch: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}/member-search`,
    organizationAddMember: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}/members`,
    claims: '/api/admin/project-claims',
    claimApprove: (id: string) => `/api/admin/project-claims/${encodeURIComponent(id)}/approve`,
    claimReject: (id: string) => `/api/admin/project-claims/${encodeURIComponent(id)}/reject`,
    projectMembers: (id: string) => `/api/admin/projects/${encodeURIComponent(id)}/members`,
    userRename: (id: string) => `/api/admin/users/${encodeURIComponent(id)}/name`,
    syncGithub: '/api/admin/sync/github',
  },
  dev: {
    projects: '/api/dev/projects',
    projectDetail: (id: string) => `/api/dev/projects/${encodeURIComponent(id)}`,
    projectUserSearch: (id: string) => `/api/dev/projects/${encodeURIComponent(id)}/users/search`,
    projectMembers: (id: string) => `/api/dev/projects/${encodeURIComponent(id)}/members`,
    feedback: '/api/dev/feedback',
    feedbackDetail: (id: string) => `/api/dev/feedback/${encodeURIComponent(id)}`,
    feedbackReplies: (id: string) => `/api/dev/feedback/${encodeURIComponent(id)}/replies`,
    comments: '/api/dev/comments',
    commentDetail: (id: string) => `/api/dev/comments/${encodeURIComponent(id)}`,
    commentReplies: (id: string) => `/api/dev/comments/${encodeURIComponent(id)}/replies`,
    stats: '/api/dev/stats',
    organizations: '/api/dev/organizations',
    organizationDetail: (id: string) => `/api/dev/organizations/${encodeURIComponent(id)}`,
    organizationMembers: (id: string) => `/api/dev/organizations/${encodeURIComponent(id)}/members`,
    projectClaims: '/api/dev/project-claims',
  },
  users: {
    profile: (name: string) => `/api/users/${encodeURIComponent(name)}/profile`,
    comments: (name: string) => `/api/users/${encodeURIComponent(name)}/comments`,
    projects: (name: string) => `/api/users/${encodeURIComponent(name)}/projects`,
    organizations: (name: string) => `/api/users/${encodeURIComponent(name)}/organizations`,
  },
} as const;

export type DevEndpoints = typeof API.dev;
