export const API = {
  auth: {
    login: '/api/auth/login',
    callback: '/api/auth/callback',
    me: '/api/auth/me',
    logout: '/api/auth/logout',
    capabilities: '/api/capabilities',
    userAvatar: '/api/user/avatar',
  },
  catalog: {
    categories: '/api/categories',
    projects: '/api/projects',
    stats: '/api/stats',
    stories: '/api/stories',
  },
  feedback: {
    list: '/api/feedback',
    detail: (id: string) => `/api/feedback/${encodeURIComponent(id)}`,
    replies: (id: string) => `/api/feedback/${encodeURIComponent(id)}/replies`,
  },
  upload: {
    image: '/api/upload',
  },
  submissions: {
    list: '/api/submissions',
    dev: '/api/dev/submissions',
  },
  admin: {
    categories: '/api/admin/categories',
    projects: '/api/admin/projects',
    submissions: '/api/admin/submissions',
    moderationComments: '/api/admin/moderation/comments',
    moderationBugs: '/api/admin/moderation/bugs',
    users: '/api/admin/users',
    auditLogs: '/api/admin/audit-logs',
    media: '/api/admin/media',
    dashboard: '/api/admin/dashboard',
    roleTemplates: '/api/admin/role-templates',
    mediaTags: (id: string) => `/api/admin/media/${encodeURIComponent(id)}/tags`,
    mediaBatchTag: '/api/admin/media/batch-tag',
    mediaBatchDelete: '/api/admin/media/batch-delete',
    organizations: '/api/admin/organizations',
    organizationDetail: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}`,
    organizationApprove: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}/approve`,
    organizationReject: (id: string) => `/api/admin/organizations/${encodeURIComponent(id)}/reject`,
    claims: '/api/admin/project-claims',
    claimApprove: (id: string) => `/api/admin/project-claims/${encodeURIComponent(id)}/approve`,
    claimReject: (id: string) => `/api/admin/project-claims/${encodeURIComponent(id)}/reject`,
    projectMembers: (id: string) => `/api/admin/projects/${encodeURIComponent(id)}/members`,
  },
  dev: {
    projects: '/api/dev/projects',
    projectDetail: (id: string) => `/api/dev/projects/${encodeURIComponent(id)}`,
    projectMembers: (id: string) => `/api/dev/projects/${encodeURIComponent(id)}/members`,
    feedback: '/api/dev/feedback',
    feedbackDetail: (id: string) => `/api/dev/feedback/${encodeURIComponent(id)}`,
    feedbackReplies: (id: string) => `/api/dev/feedback/${encodeURIComponent(id)}/replies`,
    comments: '/api/dev/comments',
    commentDetail: (id: string) => `/api/dev/comments/${encodeURIComponent(id)}`,
    commentReplies: (id: string) => `/api/dev/comments/${encodeURIComponent(id)}/replies`,
    stats: '/api/dev/stats',
    organizations: '/api/dev/organizations',
    organizationDetail: (id: string) => `/api/dev/organizations/${encodeURIComponent(id)}`,
    organizationMembers: (id: string) => `/api/dev/organizations/${encodeURIComponent(id)}/members`,
    projectClaims: '/api/dev/project-claims',
  },
} as const;

export type DevEndpoints = typeof API.dev;
